// TODO: Move this to a DB
const data = [
  {
    name: 'Destinations for arts & culture',
    locations: [
      { city: 'Phoenix', state: 'Arizona' },
      { city: 'Hot Springs', state: 'Arkansas' },
      { city: 'Los Angeles', state: 'California' },
      { city: 'San Diego', state: 'California' },
      { city: 'San Francisco', state: 'California' },
      { city: 'Barcelona', state: 'Catalonia' },
      { city: 'Prague', state: 'Czechia' },
      { city: 'Washington', state: 'District of Columbia' },
      { city: 'Keswick', state: 'England' },
      { city: 'London', state: 'England' },
      { city: 'Scarborough', state: 'England' },
      { city: 'Sherwood Forest', state: 'England' },
      { city: 'York', state: 'England' },
      { city: 'Paris', state: 'France' },
      { city: 'Rhodes', state: 'Greece' },
      { city: 'Nashville', state: 'Indiana' },
      { city: 'Dublin', state: 'Ireland' },
      { city: 'Florence', state: 'Italy' },
      { city: 'Rome', state: 'Italy' },
      { city: 'Lisbon', state: 'Lisbon' },
      { city: 'Grande Isle', state: 'Louisiana' },
      { city: 'New Orleans', state: 'Louisiana' },
      { city: 'Marthas Vineyard', state: 'Massachusetts' },
      { city: 'South Haven', state: 'Michigan' },
      { city: 'Duluth', state: 'Minnesota' },
      { city: 'Amsterdam', state: 'Netherlands' },
      { city: 'New York', state: 'New York' },
      { city: 'Nice', state: "Provence-Alpes-Côte d'Azur" },
      { city: 'Inverness', state: 'Scotland' },
      { city: 'Malaga', state: 'Spain' },
      { city: 'Valencia', state: 'Spain' },
      { city: 'Split', state: 'Split-Dalmatia County' },
      { city: 'Nashville', state: 'Tennessee' },
      { city: 'Austin', state: 'Texas' },
      { city: 'Houston', state: 'Texas' },
      { city: 'Darthmouth', state: 'United Kingdom' },
      { city: 'Edinburgh', state: 'United Kingdom' },
      { city: 'Liverpool', state: 'United Kingdom' },
      { city: 'St Ives', state: 'United Kingdom' },
      { city: 'Lake Powell', state: 'United States' },
      { city: 'Lake Anna', state: 'Virginia' },
      { city: 'Leavenworth', state: 'Washington' },
      { city: 'Seattle', state: 'Washington' },
    ],
  },
];

// This could be data from an api
export const getAwayDestinations = async () => data;
